
CC = clang
CC_FLAGS = -std=c11 -O2 -Iinclude
#CC_FLAGS = -Weverything -Wno-padded -std=c11 -O0 -g -Iinclude

#CC = gcc
#CC_FLAGS = -Wall -Wextra -std=c11 -O0 -g -Iinclude

EXEC = blackjack

$(EXEC): main.o blackjack.o
	$(CC) main.o blackjack.o -o $(EXEC)

main.o: src/main.c
	$(CC) -c $(CC_FLAGS) src/main.c -o main.o

blackjack.o: src/blackjack.c
	$(CC) -c $(CC_FLAGS) src/blackjack.c -o blackjack.o

clean:
	rm -f $(EXEC) *.o *~
